name: tappuu_website
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Core
  get: ^4.7.3
  intl: ^0.20.2
  http: ^1.6.0
  path: ^1.8.0
  shared_preferences: ^2.5.4
  cached_network_image: ^3.4.1
  flutter_cache_manager: ^3.4.1 # :contentReference[oaicite:0]{index=0}

  # UI
  google_fonts: ^6.3.3
  skeletonizer: ^2.1.2
  shimmer: ^3.0.0
  flutter_screenutil: ^5.9.3
  dotted_border: 2.1.0
  flutter_svg: ^2.0.5
  smooth_page_indicator: ^2.0.1
  url_launcher: ^6.1.5
  translator: ^1.0.3+1


  # Maps & location
  flutter_map: ^8.2.2
  geolocator: ^14.0.2

  # Media / files
  image_picker: ^1.2.1 # :contentReference[oaicite:1]{index=1}
  image_picker_web: ^4.0.0 # :contentReference[oaicite:2]{index=2}
  file_picker: ^10.3.8 # :contentReference[oaicite:3]{index=3}
  video_player: ^2.5.1
  chewie: ^1.5.0
  audioplayers: ^6.5.1

  # Firebase (متوافق مع web الحديثة)
  firebase_core: ^4.3.0 # :contentReference[oaicite:4]{index=4}
  firebase_auth: ^6.1.3 # :contentReference[oaicite:5]{index=5}
  firebase_messaging: ^16.1.0 # :contentReference[oaicite:6]{index=6}

  # Deep links & share (حل التعارض)
  app_links: ^7.0.0 # 
  share_plus: ^12.0.1 # :contentReference[oaicite:8]{index=8}

  permission_handler: ^12.0.1
  googleapis_auth: ^2.0.0
  speech_to_text: ^7.3.0

  # WebView (لو أنت فعلاً تستخدمها بالمشروع)
  webview_flutter: ^4.13.0
  webview_flutter_wkwebview: ^3.23.5 # :contentReference[oaicite:9]{index=9}
  webview_flutter_web: ^0.2.3+4 # :contentReference[oaicite:10]{index=10}

  # Web helpers
  universal_html: ^2.2.1
  js: ^0.7.2
  g_recaptcha_v3: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.4
  flutter_launcher_icons: ^0.14.4

flutter_native_splash:
  color: "#F2B81B"
  image: "assets/images/logo-png-Black.png"
  android: true
  ios: true
  web: true
  fullscreen: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/play_store_512.png"
  adaptive_icon_background: "#F2B81B"
  adaptive_icon_foreground: "assets/images/logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/
    - assets/images/
  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Tajawal-Light.ttf
          weight: 300
        - asset: assets/fonts/Tajawal-Regular.ttf
          weight: 400
        - asset: assets/fonts/Tajawal-Medium.ttf
          weight: 500
        - asset: assets/fonts/Tajawal-Bold.ttf
          weight: 700
        - asset: assets/fonts/Tajawal-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Tajawal-Black.ttf
          weight: 900
