name: tappuu_website
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter



  
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  http: ^1.0.0
  cached_network_image: ^3.2.0
  shared_preferences: ^2.0.15
  path: ^1.8.0
  google_fonts: ^6.2.0
  skeletonizer: ^1.4.2
  flutter_map: ^7.0.2
  geolocator: ^11.0.0
  image_picker: ^0.8.7+5
  image_picker_web: ^4.0.0

  translator: ^1.0.3+1
  smooth_page_indicator: ^1.1.0
  url_launcher: ^6.1.5
  app_links: ^5.0.0
  share_plus: ^9.0.0
  get: ^4.6.7
  shimmer: ^3.0.0
  flutter_screenutil: ^5.9.3
  flutter_cache_manager: ^3.3.0
  dotted_border: ^2.1.0
  file_picker: ^5.2.3         # لاختيار ملفات من الجهاز
  video_player: ^2.5.1        # لمعاينة الفيديوهات
  firebase_core: ^2.18.0
  firebase_auth: ^4.12.1
  firebase_messaging: ^14.7.0
  chewie: ^1.5.0
  flutter_native_splash: ^2.4.4
  flutter_launcher_icons: ^0.14.4
  flutter_svg: ^2.0.5 
  googleapis_auth: ^1.5.0
  speech_to_text: ^6.3.0
  audioplayers: ^5.0.0 
  webview_flutter: ^4.4.0
  webview_flutter_wkwebview: 3.17.0
  webview_flutter_web: ^0.2.3+4   
  universal_html: ^2.2.1
  js: ^0.6.7
  g_recaptcha_v3: ^0.0.5


  

dependency_overrides:
  firebase_auth_web: ^5.9.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  
flutter_native_splash:
  color: "#F2B81B"
  image: "assets/images/logo-png-Black.png"
  android: true
  ios: true
  web: true
  fullscreen: true  # اجعل الشاشة بالكامل بدون عناصر واجهة المستخدم الأخرى

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/play_store_512.png"
  adaptive_icon_background: "#F2B81B"
  adaptive_icon_foreground: "assets/images/logo.png"
  min_sdk_android: 21


flutter:

  uses-material-design: true

  

  assets:
   - assets/
   - assets/fonts/
   - assets/images/
  

  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Tajawal-Light.ttf
          weight: 300
        - asset: assets/fonts/Tajawal-Regular.ttf
          weight: 400
        - asset: assets/fonts/Tajawal-Medium.ttf
          weight: 500
        - asset: assets/fonts/Tajawal-Bold.ttf
          weight: 700
        - asset: assets/fonts/Tajawal-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Tajawal-Black.ttf
          weight: 900